name: islamic_study_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+3

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  flutter_localizations:
    sdk: flutter
  share_plus: ^10.1.3
  flutter_svg: ^2.0.10+1
  flutter_launcher_icons: ^0.14.4
  provider: ^6.1.1
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  http: ^1.6.0
  shimmer: ^3.0.0
  shared_preferences: ^2.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
  - assets/profile_picture.jpg

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: "assets/appIcon.png"

   